version: "3"

services: 
    mongodb:
        image: mongo:4.0.14
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - db-data:/data/db
        ports:
            - 27017:27017
        command: mongod --logpath=/dev/null # --quiet

volumes:
  db-data:
