version: "3.5"

services:
  app:
    container_name: "app"
    build:
      context: .docker/dev
      dockerfile: Dockerfile
      target: dev
    working_dir: /home/app
    restart: unless-stopped
    command: bash -c "go mod download && make serve"
    environment:
      DEBUG: "true"
      SERVING_PORT: ":${APP_PORT:-80}"
    ports:
        - "${APP_PORT:-80}:${APP_PORT:-80}"
    volumes:
      - .:/home/app
    networks:
      - app

  mongodb:
    container_name: "mongodb"
    image: mongo:4.4.0
    command: mongod --logpath=/dev/null # --quiet
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - ${DB_PORT:-27017}:27017
    volumes:
      - db-data:/data/db
    networks:
      - app

networks:
  app:
    name: app_network

volumes:
  db-data:
